name: React

on: [push, pull_request]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set project dir environment var
        run: echo ::set-env name=PROJECT_DIR::"$GITHUB_WORKSPACE/client"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
        
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set project dir environment var
        run: echo ::set-env name=PROJECT_DIR::"$GITHUB_WORKSPACE/client"

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript compiler
        run: npm run typescript
        
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - name: Set project dir environment var
        run: echo ::set-env name=PROJECT_DIR::"$GITHUB_WORKSPACE/client"

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
